/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:5132987b-853d-4d97-87cf-509003d417f0",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_pt4YC6xkc",
    "aws_user_pools_web_client_id": "2sovr8csqf2ihopddidjnljl6m",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "PREFERRED_USERNAME"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://vodqokgmirdn5bdvr66rprf6fu.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-atesad3tlvbobmbogtcndjmbai",
    "aws_user_files_s3_bucket": "awsamplify6b6762a73a3046b18889ad645905f67a91913-staging",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
